services:
  db:
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
      SA_PASSWORD: "${DATABASE_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ${DATAFILE_PATH}:/tmp/mrds.csv
      - ${MSSQL_PATH}:/var/opt/mssql
